version: 2
jobs:
  build:
    # this is the directory into which our code will be checked out
    working_directory: ~/repo

    # get the docker image
    docker:
      - image: circleci/android:api-28-alpha

    # put here all the environment variables
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  bump_version:
    # this is the directory into which our code will be checked out
    working_directory: ~/repo

    # get the docker image
    docker:
      - image: circleci/android:api-28-alpha

    # put here all the environment variables
    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Testando o script
          command: |
            cd scripts
            ./testingCircleCI.sh
            echo "o mundo é bão, Sebastião"
            printf "\n"
            echo "-- Pushing To Github --"
            printf "\n"
            git config credential.helper 'cache --timeout=120'
            git config user.email ${GITHUB_EMAIL}
            git config user.name ${GITHUB_USERNAME}
            git add ../app/build.gradle
            git commit -m "Bumping Project Version [ci skip]"
            cd ..
            git push https://${GITHUB_API_TOKEN}@github.com/${GITHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git ${CIRCLE_BRANCH}

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - bump_version
